# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MFAM_Loader
                                 A QGIS plugin
 This plugin will load MFAM data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-09-11
        copyright            : (C) 2018 by Acme
        email                : Jack@home
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MFAM_Loader class from file MFAM_Loader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .mfam1 import MFAM_Loader
    return MFAM_Loader(iface)
