# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mfam1_dockwidget_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MFAM_LoaderDockWidgetBase(object):
    def setupUi(self, MFAM_LoaderDockWidgetBase):
        MFAM_LoaderDockWidgetBase.setObjectName("MFAM_LoaderDockWidgetBase")
        MFAM_LoaderDockWidgetBase.resize(770, 1038)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MFAM_LoaderDockWidgetBase.setPalette(palette)
        self.dockWidget = QtWidgets.QWidget()
        self.dockWidget.setObjectName("dockWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.line = QtWidgets.QFrame(self.dockWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 15, 2, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.dockWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 2, 2, 1, 1)
        self.clear_List = QtWidgets.QPushButton(self.dockWidget)
        self.clear_List.setObjectName("clear_List")
        self.gridLayout.addWidget(self.clear_List, 11, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.dockWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 8, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.dockWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 7, 2, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.dockWidget)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 9, 2, 1, 1)
        self.outputCheckBox = QtWidgets.QCheckBox(self.dockWidget)
        self.outputCheckBox.setObjectName("outputCheckBox")
        self.gridLayout.addWidget(self.outputCheckBox, 18, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.dockWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 12, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 9, 0, 1, 1)
        self.Drone_button = QtWidgets.QRadioButton(self.dockWidget)
        self.Drone_button.setChecked(True)
        self.Drone_button.setObjectName("Drone_button")
        self.gridLayout.addWidget(self.Drone_button, 0, 2, 1, 1)
        self.outputFileName = QgsFileWidget(self.dockWidget)
        self.outputFileName.setFileWidgetButtonVisible(False)
        self.outputFileName.setObjectName("outputFileName")
        self.gridLayout.addWidget(self.outputFileName, 22, 2, 1, 1)
        self.load_files = QtWidgets.QPushButton(self.dockWidget)
        self.load_files.setObjectName("load_files")
        self.gridLayout.addWidget(self.load_files, 4, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.dockWidget)
        self.label_3.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.sampleRateSpin = QgsDoubleSpinBox(self.dockWidget)
        self.sampleRateSpin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sampleRateSpin.setObjectName("sampleRateSpin")
        self.horizontalLayout.addWidget(self.sampleRateSpin)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 14, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.dockWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 21, 2, 1, 1)
        self.process_files = QtWidgets.QPushButton(self.dockWidget)
        self.process_files.setObjectName("process_files")
        self.gridLayout.addWidget(self.process_files, 13, 2, 1, 1)
        self.MplWindow = MatplotlibWidget(self.dockWidget)
        self.MplWindow.setMinimumSize(QtCore.QSize(0, 200))
        self.MplWindow.setMaximumSize(QtCore.QSize(16777215, 250))
        self.MplWindow.setObjectName("MplWindow")
        self.gridLayout.addWidget(self.MplWindow, 10, 2, 1, 1)
        MFAM_LoaderDockWidgetBase.setWidget(self.dockWidget)

        self.retranslateUi(MFAM_LoaderDockWidgetBase)
        QtCore.QMetaObject.connectSlotsByName(MFAM_LoaderDockWidgetBase)

    def retranslateUi(self, MFAM_LoaderDockWidgetBase):
        _translate = QtCore.QCoreApplication.translate
        MFAM_LoaderDockWidgetBase.setWindowTitle(_translate("MFAM_LoaderDockWidgetBase", "mfam_loader"))
        self.radioButton_2.setText(_translate("MFAM_LoaderDockWidgetBase", "Magview MFAM"))
        self.clear_List.setText(_translate("MFAM_LoaderDockWidgetBase", "Clear List"))
        self.label_2.setText(_translate("MFAM_LoaderDockWidgetBase", "List of Files for Processing:"))
        self.outputCheckBox.setText(_translate("MFAM_LoaderDockWidgetBase", "Generate an output file"))
        self.Drone_button.setText(_translate("MFAM_LoaderDockWidgetBase", "Drone Data"))
        self.load_files.setText(_translate("MFAM_LoaderDockWidgetBase", "Select MFAM file(s)"))
        self.label_3.setText(_translate("MFAM_LoaderDockWidgetBase", "Sampling Rate Detected (Hz):"))
        self.label.setText(_translate("MFAM_LoaderDockWidgetBase", "Output File (*.txt)"))
        self.process_files.setText(_translate("MFAM_LoaderDockWidgetBase", "Process File(s)"))

from matplotlibwidget import MatplotlibWidget
from qgsdoublespinbox import QgsDoubleSpinBox
from qgsfilewidget import QgsFileWidget
